// WHO/FAO Essential Amino Acid Requirements (for 70kg adult)
export const WHO_CONSTRAINTS = {
  histidine: { min: 700, max: 5000, unit: "mg" },
  isoleucine: { min: 1400, max: 10000, unit: "mg" },
  leucine: { min: 2730, max: 15000, unit: "mg" },
  lysine: { min: 2100, max: 10000, unit: "mg" },
  methionine: { min: 1050, max: 8000, unit: "mg" },
  phenylalanine: { min: 1750, max: 10000, unit: "mg" },
  threonine: { min: 1050, max: 8000, unit: "mg" },
  tryptophan: { min: 280, max: 3000, unit: "mg" },
  valine: { min: 1820, max: 12000, unit: "mg" },
};

export interface Food {
  id: string;
  name: string;
  category: string;
  cost: number; // USD per 100g
  // Essential amino acids (mg per 100g)
  histidine: number;
  isoleucine: number;
  leucine: number;
  lysine: number;
  methionine: number;
  phenylalanine: number;
  threonine: number;
  tryptophan: number;
  valine: number;
  // Other nutrients (for display)
  energy?: number; // kcal per 100g
  protein?: number; // g per 100g
  carbs?: number;
  fat?: number;
  fiber?: number;
  calcium?: number; // mg per 100g
  iron?: number;
  vitaminC?: number;
}

// Foods with amino acid data (mg per 100g)
export const USDA_FOODS: Food[] = [
  {
    id: "chicken_breast",
    name: "Chicken Breast",
    category: "Protein",
    cost: 0.80,
    histidine: 1030,
    isoleucine: 1430,
    leucine: 2480,
    lysine: 2790,
    methionine: 870,
    phenylalanine: 1260,
    threonine: 1390,
    tryptophan: 370,
    valine: 1510,
    energy: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    calcium: 15,
    iron: 1,
    vitaminC: 0,
  },
  {
    id: "eggs",
    name: "Eggs (whole)",
    category: "Protein",
    cost: 0.35,
    histidine: 320,
    isoleucine: 680,
    leucine: 1090,
    lysine: 910,
    methionine: 390,
    phenylalanine: 680,
    threonine: 610,
    tryptophan: 170,
    valine: 850,
    energy: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    calcium: 56,
    iron: 1.8,
    vitaminC: 0,
  },
  {
    id: "soybeans",
    name: "Soybeans (mature)",
    category: "Legumes",
    cost: 0.25,
    histidine: 1100,
    isoleucine: 1970,
    leucine: 3300,
    lysine: 2700,
    methionine: 550,
    phenylalanine: 2120,
    threonine: 1680,
    tryptophan: 590,
    valine: 2030,
    energy: 173,
    protein: 16.6,
    carbs: 9.9,
    fat: 9,
    fiber: 6,
    calcium: 102,
    iron: 5.14,
    vitaminC: 6,
  },
  {
    id: "milk",
    name: "Milk (whole)",
    category: "Dairy",
    cost: 0.08,
    histidine: 90,
    isoleucine: 200,
    leucine: 320,
    lysine: 270,
    methionine: 80,
    phenylalanine: 160,
    threonine: 150,
    tryptophan: 40,
    valine: 220,
    energy: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    calcium: 113,
    iron: 0.03,
    vitaminC: 0,
  },
  {
    id: "beef",
    name: "Beef (ground, lean)",
    category: "Protein",
    cost: 1.20,
    histidine: 990,
    isoleucine: 1370,
    leucine: 2350,
    lysine: 2550,
    methionine: 760,
    phenylalanine: 1180,
    threonine: 1280,
    tryptophan: 300,
    valine: 1470,
    energy: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    calcium: 18,
    iron: 2.6,
    vitaminC: 0,
  },
  {
    id: "peanuts",
    name: "Peanuts",
    category: "Nuts",
    cost: 0.45,
    histidine: 680,
    isoleucine: 920,
    leucine: 1670,
    lysine: 930,
    methionine: 320,
    phenylalanine: 1370,
    threonine: 880,
    tryptophan: 250,
    valine: 1080,
    energy: 567,
    protein: 25.8,
    carbs: 16,
    fat: 49,
    fiber: 8.5,
    calcium: 92,
    iron: 4.6,
    vitaminC: 0,
  },
  {
    id: "oats",
    name: "Oats",
    category: "Grains",
    cost: 0.18,
    histidine: 430,
    isoleucine: 810,
    leucine: 1360,
    lysine: 700,
    methionine: 310,
    phenylalanine: 960,
    threonine: 590,
    tryptophan: 230,
    valine: 930,
    energy: 389,
    protein: 16.9,
    carbs: 66,
    fat: 6.9,
    fiber: 10.6,
    calcium: 54,
    iron: 4.7,
    vitaminC: 0,
  },
  {
    id: "quinoa",
    name: "Quinoa (cooked)",
    category: "Grains",
    cost: 0.40,
    histidine: 390,
    isoleucine: 460,
    leucine: 840,
    lysine: 760,
    methionine: 310,
    phenylalanine: 590,
    threonine: 430,
    tryptophan: 170,
    valine: 580,
    energy: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    fiber: 2.8,
    calcium: 17,
    iron: 1.5,
    vitaminC: 0,
  },
  // Amino acid supplements
  {
    id: "l_leucine",
    name: "L-Leucine Powder",
    category: "Supplement",
    cost: 2.50,
    histidine: 0,
    isoleucine: 0,
    leucine: 100000, // Pure leucine
    lysine: 0,
    methionine: 0,
    phenylalanine: 0,
    threonine: 0,
    tryptophan: 0,
    valine: 0,
    energy: 0,
    protein: 0,
  },
  {
    id: "l_lysine",
    name: "L-Lysine Powder",
    category: "Supplement",
    cost: 2.20,
    histidine: 0,
    isoleucine: 0,
    leucine: 0,
    lysine: 100000, // Pure lysine
    methionine: 0,
    phenylalanine: 0,
    threonine: 0,
    tryptophan: 0,
    valine: 0,
    energy: 0,
    protein: 0,
  },
  {
    id: "l_isoleucine",
    name: "L-Isoleucine Powder",
    category: "Supplement",
    cost: 2.80,
    histidine: 0,
    isoleucine: 100000, // Pure isoleucine
    leucine: 0,
    lysine: 0,
    methionine: 0,
    phenylalanine: 0,
    threonine: 0,
    tryptophan: 0,
    valine: 0,
    energy: 0,
    protein: 0,
  },
  {
    id: "l_valine",
    name: "L-Valine Powder",
    category: "Supplement",
    cost: 2.60,
    histidine: 0,
    isoleucine: 0,
    leucine: 0,
    lysine: 0,
    methionine: 0,
    phenylalanine: 0,
    threonine: 0,
    tryptophan: 0,
    valine: 100000, // Pure valine
    energy: 0,
    protein: 0,
  },
  {
    id: "l_histidine",
    name: "L-Histidine Powder",
    category: "Supplement",
    cost: 3.00,
    histidine: 100000, // Pure histidine
    isoleucine: 0,
    leucine: 0,
    lysine: 0,
    methionine: 0,
    phenylalanine: 0,
    threonine: 0,
    tryptophan: 0,
    valine: 0,
    energy: 0,
    protein: 0,
  },
  {
    id: "l_threonine",
    name: "L-Threonine Powder",
    category: "Supplement",
    cost: 2.40,
    histidine: 0,
    isoleucine: 0,
    leucine: 0,
    lysine: 0,
    methionine: 0,
    phenylalanine: 0,
    threonine: 100000, // Pure threonine
    tryptophan: 0,
    valine: 0,
    energy: 0,
    protein: 0,
  },
  {
    id: "l_phenylalanine",
    name: "L-Phenylalanine Powder",
    category: "Supplement",
    cost: 2.70,
    histidine: 0,
    isoleucine: 0,
    leucine: 0,
    lysine: 0,
    methionine: 0,
    phenylalanine: 100000, // Pure phenylalanine
    threonine: 0,
    tryptophan: 0,
    valine: 0,
    energy: 0,
    protein: 0,
  },
  {
    id: "l_methionine",
    name: "L-Methionine Powder",
    category: "Supplement",
    cost: 2.90,
    histidine: 0,
    isoleucine: 0,
    leucine: 0,
    lysine: 0,
    methionine: 100000, // Pure methionine
    phenylalanine: 0,
    threonine: 0,
    tryptophan: 0,
    valine: 0,
    energy: 0,
    protein: 0,
  },
  {
    id: "l_tryptophan",
    name: "L-Tryptophan Powder",
    category: "Supplement",
    cost: 3.50,
    histidine: 0,
    isoleucine: 0,
    leucine: 0,
    lysine: 0,
    methionine: 0,
    phenylalanine: 0,
    threonine: 0,
    tryptophan: 100000, // Pure tryptophan
    valine: 0,
    energy: 0,
    protein: 0,
  },
];
