// WHO Recommended Daily Allowances (simplified)
export const WHO_CONSTRAINTS = {
  energy: { min: 2000, max: 2500, unit: "kcal" },
  protein: { min: 50, max: 200, unit: "g" },
  carbs: { min: 225, max: 325, unit: "g" },
  fat: { min: 44, max: 78, unit: "g" },
  fiber: { min: 25, max: 100, unit: "g" },
  calcium: { min: 1000, max: 2500, unit: "mg" },
  iron: { min: 8, max: 45, unit: "mg" },
  vitaminC: { min: 75, max: 2000, unit: "mg" },
};

export interface Food {
  id: string;
  name: string;
  category: string;
  cost: number; // USD per 100g
  energy: number; // kcal per 100g
  protein: number; // g per 100g
  carbs: number;
  fat: number;
  fiber: number;
  calcium: number; // mg per 100g
  iron: number;
  vitaminC: number;
}

// USDA Food Database (simplified selection)
export const USDA_FOODS: Food[] = [
  {
    id: "rice",
    name: "White Rice",
    category: "Grains",
    cost: 0.15,
    energy: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    calcium: 10,
    iron: 0.2,
    vitaminC: 0,
  },
  {
    id: "beans",
    name: "Black Beans",
    category: "Legumes",
    cost: 0.25,
    energy: 132,
    protein: 8.9,
    carbs: 23.7,
    fat: 0.5,
    fiber: 8.7,
    calcium: 35,
    iron: 2.1,
    vitaminC: 0,
  },
  {
    id: "chicken",
    name: "Chicken Breast",
    category: "Protein",
    cost: 0.80,
    energy: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    calcium: 15,
    iron: 1,
    vitaminC: 0,
  },
  {
    id: "eggs",
    name: "Eggs",
    category: "Protein",
    cost: 0.35,
    energy: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    calcium: 56,
    iron: 1.8,
    vitaminC: 0,
  },
  {
    id: "milk",
    name: "Milk (2%)",
    category: "Dairy",
    cost: 0.08,
    energy: 50,
    protein: 3.3,
    carbs: 4.8,
    fat: 2,
    fiber: 0,
    calcium: 120,
    iron: 0.03,
    vitaminC: 0,
  },
  {
    id: "broccoli",
    name: "Broccoli",
    category: "Vegetables",
    cost: 0.22,
    energy: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
    calcium: 47,
    iron: 0.7,
    vitaminC: 89,
  },
  {
    id: "carrots",
    name: "Carrots",
    category: "Vegetables",
    cost: 0.12,
    energy: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    calcium: 33,
    iron: 0.3,
    vitaminC: 6,
  },
  {
    id: "banana",
    name: "Banana",
    category: "Fruits",
    cost: 0.18,
    energy: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    calcium: 5,
    iron: 0.3,
    vitaminC: 9,
  },
  {
    id: "orange",
    name: "Orange",
    category: "Fruits",
    cost: 0.20,
    energy: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
    calcium: 40,
    iron: 0.1,
    vitaminC: 53,
  },
  {
    id: "oats",
    name: "Oats",
    category: "Grains",
    cost: 0.18,
    energy: 389,
    protein: 16.9,
    carbs: 66,
    fat: 6.9,
    fiber: 10.6,
    calcium: 54,
    iron: 4.7,
    vitaminC: 0,
  },
  {
    id: "peanuts",
    name: "Peanuts",
    category: "Nuts",
    cost: 0.45,
    energy: 567,
    protein: 25.8,
    carbs: 16,
    fat: 49,
    fiber: 8.5,
    calcium: 92,
    iron: 4.6,
    vitaminC: 0,
  },
  {
    id: "potato",
    name: "Potato",
    category: "Vegetables",
    cost: 0.10,
    energy: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.2,
    calcium: 12,
    iron: 0.8,
    vitaminC: 20,
  },
];
